server:
  port: 8202

spring:
  application:
    name: service-cmn
  datasource:
    username: root
    url: jdbc:mysql://192.168.204.129:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.139:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


