

#服务器端口
server:
  port: 8203

#应用名
spring:
  application:
    name: service-hosp
    #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.204.129:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456


    #全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

   # mongodb 数据库
  data:
    mongodb:
      uri: mongodb://192.168.204.133:27017/yygh_hosp

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.139:8848

#mapper位置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



