

#服务器端口
server:
  port: 8021

#应用名
spring:
  application:
    name: service-hosp
    #环境配置
  profiles:
    active: dev
    #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.204.129:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    #全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    #mapper位置
mybatis-plus:
  mapper-locations:classpath:/com/atguigu/hosp/mapper/xml/*.xml

